-- ─────────────────────────────────────────────────────────────
-- PhD Match DE — Initial Seed Data
-- All institutions/programmes below exist; verify current
-- deadlines & funding on the official programme website.
-- ─────────────────────────────────────────────────────────────

-- INSTITUTIONS ────────────────────────────────────────────────
insert into institutions (id, name, short_name, city, state, type, website, description) values
  ('11111111-0000-0000-0000-000000000001', 'Deutsches Krebsforschungszentrum', 'DKFZ', 'Heidelberg', 'Baden-Württemberg', 'helmholtz', 'https://www.dkfz.de', 'Größtes biomedizinisches Forschungs­zentrum Deutschlands mit Fokus auf Krebs­forschung. Helmholtz-Gemeinschaft.'),
  ('11111111-0000-0000-0000-000000000002', 'Deutsches Zentrum für Neurodegenerative Erkrankungen', 'DZNE', 'Bonn', 'Nordrhein-Westfalen', 'helmholtz', 'https://www.dzne.de', 'Bundesweites Helmholtz-Zentrum mit Hauptsitz Bonn und Standorten in 9 Städten. Neurodegenerative Erkrankungen.'),
  ('11111111-0000-0000-0000-000000000003', 'Max-Planck-Institut für Hirnforschung', 'MPI Brain Research', 'Frankfurt am Main', 'Hessen', 'max_planck', 'https://brain.mpg.de', 'MPI mit Fokus auf neuronale Schaltkreise, Konnektomik und Hirnfunktion.'),
  ('11111111-0000-0000-0000-000000000004', 'Max-Planck-Institut für Immunbiologie und Epigenetik', 'MPI-IE Freiburg', 'Freiburg im Breisgau', 'Baden-Württemberg', 'max_planck', 'https://www.ie-freiburg.mpg.de', 'Forschung zu Immunsystem, Epigenetik und Stoffwechsel.'),
  ('11111111-0000-0000-0000-000000000005', 'Universitätsmedizin der Goethe-Universität', 'Goethe Frankfurt', 'Frankfurt am Main', 'Hessen', 'university_hospital', 'https://www.uni-frankfurt.de', 'Großes Universitätsklinikum mit starken Onkologie- und Immunologie-Forschungsgruppen.'),
  ('11111111-0000-0000-0000-000000000006', 'Ruhr-Universität Bochum', 'RUB', 'Bochum', 'Nordrhein-Westfalen', 'university', 'https://www.ruhr-uni-bochum.de', 'Medizinische Fakultät mit Schwerpunkten Neurowissenschaften und Molekularmedizin.'),
  ('11111111-0000-0000-0000-000000000007', 'Technische Universität Dortmund', 'TU Dortmund', 'Dortmund', 'Nordrhein-Westfalen', 'university', 'https://www.tu-dortmund.de', 'TU mit Lebenswissenschafts-Programmen, eng vernetzt mit der Ruhr-Universität.'),
  ('11111111-0000-0000-0000-000000000008', 'Universität Bonn', 'Uni Bonn', 'Bonn', 'Nordrhein-Westfalen', 'university', 'https://www.uni-bonn.de', 'Exzellenz­universität mit starken Programmen in Immunologie und Neurowissenschaften.'),
  ('11111111-0000-0000-0000-000000000009', 'Universität Heidelberg', 'Uni Heidelberg', 'Heidelberg', 'Baden-Württemberg', 'university', 'https://www.uni-heidelberg.de', 'Älteste deutsche Universität, biomedizinisches Cluster mit DKFZ und EMBL.'),
  ('11111111-0000-0000-0000-00000000000a', 'Universität Bielefeld', 'Uni Bielefeld', 'Bielefeld', 'Nordrhein-Westfalen', 'university', 'https://www.uni-bielefeld.de', 'Fakultät für Biologie und Medizinische Fakultät OWL mit Schwerpunkt Zellbiologie.'),
  ('11111111-0000-0000-0000-00000000000b', 'Charité — Universitätsmedizin Berlin', 'Charité', 'Berlin', 'Berlin', 'university_hospital', 'https://www.charite.de', 'Eines der größten Universitätsklinika Europas mit BSIO (Onkologie) und NeuroCure (Neurowissenschaften).'),
  ('11111111-0000-0000-0000-00000000000c', 'European Molecular Biology Laboratory', 'EMBL Heidelberg', 'Heidelberg', 'Baden-Württemberg', 'other', 'https://www.embl.org', 'Internationales molekular­biologisches Labor mit EIPP-Doktoranden­programm.');

-- PROGRAMMES ──────────────────────────────────────────────────
insert into programmes (institution_id, name, short_name, fields, language, funding_info, is_funded, is_rolling, next_intake, website, description_de, description_ar) values
  ('11111111-0000-0000-0000-000000000001',
    'Helmholtz International Graduate School for Cancer Research',
    'HIGS DKFZ',
    array['cancer','molecular_biology','genetics','immunology'],
    'english',
    'TV-L E13 65% / Helmholtz-Stipendium · 3 Jahre',
    true, false, 'Jährlich, Herbst-Bewerbung',
    'https://www.dkfz.de/en/phd-program',
    'Strukturiertes Promotionsprogramm im größten Krebsforschungszentrum Deutschlands. Internationale Bewerbungen ausdrücklich erwünscht. Englisch als Arbeitssprache.',
    'برنامج دكتوراه منظم في أكبر مركز أبحاث للسرطان في ألمانيا. الترحيب صريح بالطلبات الدولية. الإنجليزية لغة العمل.'
  ),
  ('11111111-0000-0000-0000-000000000002',
    'DZNE PhD Programme',
    'DZNE PhD',
    array['neuroscience','genetics','molecular_biology'],
    'english',
    'TV-L E13 65% · Vollfinanziert',
    true, true, 'Laufende Bewerbung über zentrale Stellen­börse',
    'https://www.dzne.de/en/jobs',
    'Promotionen an allen 10 DZNE-Standorten (Bonn, Magdeburg, Dresden, Tübingen, München, Göttingen, Witten, Berlin, Halle, Rostock/Greifswald). Stellen werden direkt von Arbeits­gruppen ausgeschrieben.',
    'دكتوراه في كل المواقع العشرة لـ DZNE (بون، ماغديبورغ، درسدن، توبنغن، ميونخ، غوتنغن، فيتن، برلين، هالة، روستوك/غرايفسفالد). الوظائف تُعلَن مباشرةً من مجموعات البحث.'
  ),
  ('11111111-0000-0000-0000-000000000003',
    'International Max Planck Research School for Neural Circuits',
    'IMPRS Neural Circuits',
    array['neuroscience','molecular_biology'],
    'english',
    'Vollstipendium · Max-Planck-Förderung',
    true, false, 'Jährliche Ausschreibung (typ. November–Januar)',
    'https://imprs-neuralcircuits.mpg.de',
    'Strukturiertes Doktoranden­programm gemeinsam mit MPI für Hirnforschung, Goethe-Universität und Ernst-Strüngmann-Institut. Schwerpunkt: neuronale Schaltkreise und Konnektomik.',
    'برنامج دكتوراه منظم بالتعاون بين معهد ماكس بلانك لأبحاث الدماغ، جامعة غوته، ومعهد إرنست شترونغمان. التركيز: الدوائر العصبية والكونيكتوميكس.'
  ),
  ('11111111-0000-0000-0000-000000000004',
    'IMPRS for Immunobiology, Epigenetics and Metabolism',
    'IMPRS-IEM',
    array['immunology','molecular_biology','genetics'],
    'english',
    'Vollstipendium · Max-Planck-Förderung',
    true, false, 'Jährlich, typ. Januar-Frist',
    'https://www.ie-freiburg.mpg.de/imprs',
    'Internationales Promotions­programm an der Schnittstelle von Immun­biologie, Epigenetik und Stoffwechsel. Englischsprachig.',
    'برنامج دكتوراه دولي على تقاطع علم المناعة وعلم التخلق والتمثيل الغذائي. باللغة الإنجليزية.'
  ),
  ('11111111-0000-0000-0000-000000000005',
    'Frankfurt Cancer Institute PhD Programme',
    'FCI PhD',
    array['cancer','immunology','molecular_biology'],
    'english',
    'Vollfinanziert · TV-L E13 65%',
    true, false, 'Jährliche Aus­schreibung',
    'https://www.frankfurt-cancer-institute.de',
    'LOEWE-Zentrum mit Fokus auf personalisierte Krebs­therapie und Tumor-Immunologie. Eingebettet in Universitätsklinikum Frankfurt.',
    'مركز LOEWE يركز على علاج السرطان المخصص وعلم المناعة الورمي. مدمج في مستشفى جامعة فرانكفورت.'
  ),
  ('11111111-0000-0000-0000-000000000006',
    'International Graduate School of Neuroscience',
    'IGSN Bochum',
    array['neuroscience'],
    'english',
    'Vielfältige Förderquellen · meist TV-L E13',
    true, false, 'Jährliche Aus­schreibung (typ. Februar)',
    'https://www.igsn.ruhr-uni-bochum.de',
    'Internationales Promotions­programm der Ruhr-Universität Bochum mit Schwerpunkt auf System-, Verhaltens- und kognitiver Neurowissenschaft.',
    'برنامج دكتوراه دولي في جامعة الرور بوخوم يركز على علم الأعصاب النظمي والسلوكي والإدراكي.'
  ),
  ('11111111-0000-0000-0000-000000000007',
    'Lebenswissenschaftliche Promotionsprogramme TU Dortmund',
    'TU Dortmund Life Sci',
    array['molecular_biology','genetics','structural_biology'],
    'bilingual',
    'Stellenabhängig (oft TV-L E13 50–65%)',
    true, true, 'Laufend über AG-Webseiten',
    'https://lifesciences.tu-dortmund.de',
    'Promotionen in der Fakultät Chemie und Chemische Biologie sowie Max-Planck-Institut für molekulare Physiologie (Dortmund-Campus).',
    'دكتوراه في كلية الكيمياء والبيولوجيا الكيميائية ومعهد ماكس بلانك للفيزيولوجيا الجزيئية (حرم دورتموند).'
  ),
  ('11111111-0000-0000-0000-000000000008',
    'Bonn International Graduate School Immunosciences and Infection',
    'BIGS Immunosciences',
    array['immunology','molecular_biology'],
    'english',
    'TV-L E13 65% oder Stipendium',
    true, false, 'Jährliche Aus­schreibung',
    'https://www.bigs-immunosciences.uni-bonn.de',
    'Exzellenzcluster ImmunoSensation² der Universität Bonn — strukturiertes Promotions­programm in Immun- und Infektions­wissenschaften.',
    'تجمع التميز ImmunoSensation² بجامعة بون — برنامج دكتوراه منظم في علوم المناعة والعدوى.'
  ),
  ('11111111-0000-0000-0000-000000000008',
    'Bonn International Graduate School of Neuroscience',
    'BIGS Neuroscience',
    array['neuroscience'],
    'english',
    'TV-L E13 65% oder Stipendium',
    true, false, 'Jährliche Aus­schreibung',
    'https://www.bigs-neuroscience.de',
    'Promotions­programm der Universität Bonn und des DZNE Bonn mit Fokus auf Neurodegeneration und Neuro­physiologie.',
    'برنامج دكتوراه بين جامعة بون و DZNE بون يركز على التنكس العصبي والفيزيولوجيا العصبية.'
  ),
  ('11111111-0000-0000-0000-000000000009',
    'Hartmut Hoffmann-Berling International Graduate School',
    'HBIGS Heidelberg',
    array['molecular_biology','cancer','structural_biology','genetics'],
    'english',
    'Vielfältige Förderquellen · meist TV-L E13',
    true, false, 'Jährliche Aus­schreibung',
    'https://www.hbigs.uni-heidelberg.de',
    'Großes molekular- und zellbiologisches Doktoranden­programm der Universität Heidelberg, eng vernetzt mit DKFZ und EMBL.',
    'برنامج دكتوراه كبير في البيولوجيا الجزيئية والخلوية بجامعة هايدلبرغ، مترابط بقوة مع DKFZ و EMBL.'
  ),
  ('11111111-0000-0000-0000-00000000000a',
    'Fakultät für Biologie — Doktorandenprogramme',
    'Uni Bielefeld Biology',
    array['molecular_biology','genetics','immunology'],
    'bilingual',
    'Stellenabhängig',
    true, true, 'Laufend über AG-Webseiten',
    'https://www.uni-bielefeld.de/fakultaeten/biologie',
    'Doktorarbeiten in Zellbiologie, Genetik und biomedizinischer Forschung. Stellen direkt bei Arbeits­gruppen erfragen.',
    'أعمال دكتوراه في علم الخلية والوراثة والأبحاث الطبية الحيوية. يُفضَّل التواصل المباشر مع مجموعات البحث.'
  ),
  ('11111111-0000-0000-0000-00000000000b',
    'Berlin School of Integrative Oncology',
    'BSIO Charité',
    array['cancer','immunology','molecular_biology'],
    'english',
    'Stipendium oder TV-L E13',
    true, false, 'Jährliche Aus­schreibung (typ. Januar)',
    'https://www.bsio.charite.de',
    'Strukturiertes Promotions­programm der Charité und MDC Berlin mit Fokus auf translationale Onkologie.',
    'برنامج دكتوراه منظم في Charité و MDC برلين يركز على علم الأورام الترجمي.'
  ),
  ('11111111-0000-0000-0000-00000000000b',
    'NeuroCure Graduate Programme',
    'NeuroCure',
    array['neuroscience'],
    'english',
    'Stipendium oder TV-L E13',
    true, false, 'Jährliche Aus­schreibung',
    'https://www.neurocure.de',
    'Exzellenzcluster Neurowissenschaften an der Charité — strukturiertes Promotions­programm.',
    'تجمع التميز لعلم الأعصاب في Charité — برنامج دكتوراه منظم.'
  ),
  ('11111111-0000-0000-0000-00000000000c',
    'EMBL International PhD Programme',
    'EIPP',
    array['molecular_biology','structural_biology','genetics','cancer'],
    'english',
    'Vollstipendium · EMBL-Förderung (kompetitiv, weltklasse)',
    true, false, 'Zwei Aus­schreibungen pro Jahr (typ. Januar & Juli)',
    'https://www.embl.org/about/info/phd-programme',
    'Eines der renommiertesten internationalen Promotions­programme weltweit. Sehr kompetitiv, sehr internationales Umfeld.',
    'أحد أعرق برامج الدكتوراه الدولية في العالم. تنافسي جداً وبيئة دولية بحتة.'
  );
